apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    app: worker
    type: back-tier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
      type: back-tier
  template:
    metadata:
      name: worker
      labels:
        app: worker
        type: back-tier
    spec:
      containers:
      - name: worker
        image: dockersamples/examplevotingapp_worker
